baseurl = "https://sinepy.github.io/lettertomystudents/"
googleAnalytics = "your_google_analytics_code"
hasCJKLanguage = true
languageCode = "en"
theme = "hugo-theme-cactus-plus"
title = "Letter To My Students"
[params]
about = ""
aboutauthor = "I am so interesting."
archive = ""
baiduanalytics = "your_baidu_tongji_code"
bio = "Students are awesome! Woohoo!"
copyright = ""
customcss = []
customjs = []
description = "This is a test description of letter to my students"
disqusshortname = "your_disqus_short_name"
duoshuoshortname = "your_duoshuo_short_name"
enablebaiduanalytics = false
enabledisqus = false
enableduoshuo = false
enablegithubissuestips = false
enablegoogleanalytics = false
enablerss = false
home = ""
iconfont = "font-awesome"
name = "Letter To My Students"
newerposts = ""
olderposts = ""
readmore = ""
share = ""
socialiconstyle = ""
subscribe = ""
subtitle404 = ""
tags = ""
title404 = ""
tweet = ""
twitter = "your_twitter"
[social]
facebook-square = "your_facebook_link"
github-square = "your_github_link"
twitter-square = "your_twitter_link"
